<script lang="ts">
    let count = $state(0);
</script>

<p>Counter! omg... {count}</p>
<button onclick={() => count++}>+</button>
<button onclick={() => count--}>-</button>

<p>Consequat tincidunt congue dis lacus. Odio turpis per, taciti neque mollis ligula at. Porttitor nisl mauris suscipit hac. Nascetur maecenas egestas aenean venenatis natoque augue rhoncus class vel curabitur sapien euismod. Vestibulum est aliquet, sapien semper sociosqu vivamus. Congue ornare curabitur vitae rhoncus commodo fames curae; iaculis. Accumsan porta etiam sagittis pulvinar accumsan cursus luctus aptent tristique potenti fermentum lorem. Risus habitant, felis pretium elit magnis pharetra tempus curae; convallis montes litora turpis. Non purus ornare nullam morbi varius morbi elit ipsum. Et sollicitudin duis mollis at. Placerat porttitor rhoncus ultricies. Conubia mi parturient quis penatibus suspendisse.</p>

<p>Torquent sapien id quam ante imperdiet tortor orci suspendisse congue. Eget fringilla convallis tempor eros consequat ultrices eget dictum! Sagittis nulla auctor eros magnis tincidunt leo per. Tempus lobortis egestas turpis ad accumsan himenaeos suscipit phasellus vulputate himenaeos sociosqu id! Curabitur facilisi ipsum amet congue, ultrices dapibus. Arcu eleifend quam odio elit felis convallis litora rhoncus. Semper sed purus convallis maecenas nisl accumsan. Fusce rutrum potenti per aptent tincidunt facilisis sagittis vehicula aliquet id sociosqu viverra. Habitasse mi habitant cras ac pellentesque maecenas eleifend lobortis mollis tellus risus. Himenaeos tempus aenean libero faucibus nulla et ullamcorper. Nisi elementum!</p>

<p>Posuere tempus ridiculus arcu faucibus ligula ut metus dignissim etiam condimentum per. Sagittis augue lorem pulvinar elementum ultrices lacinia phasellus habitant. Dictumst ante orci auctor habitasse suscipit dictum primis quam, molestie fermentum donec. Cras laoreet tristique, ligula suspendisse dictum. Ante mus donec vehicula aptent ultricies aenean nisl sapien mattis. Dis purus consequat mattis mollis, viverra praesent ad quis. Purus ut praesent vel euismod.</p>

<p>Purus vestibulum lobortis velit, etiam massa sed nec risus. Primis dictum taciti metus eu tempus est nam cum condimentum tempus. Luctus etiam felis pretium pretium laoreet quisque in consequat himenaeos torquent in et. Auctor urna sociis donec odio ultrices malesuada porttitor lacus dapibus. Mus molestie sagittis rhoncus amet dictum dictumst nullam. Posuere.</p>

<p>Potenti ultrices at tempor porttitor habitasse sapien. Netus phasellus malesuada commodo hendrerit bibendum aliquet aliquam. Proin enim class ante conubia! Laoreet vulputate netus mattis sem aliquet magna himenaeos posuere. Posuere condimentum placerat interdum amet nostra condimentum. Fermentum varius blandit faucibus montes varius himenaeos! Tristique, eleifend inceptos egestas habitasse dolor maecenas. Condimentum mollis litora montes sed mattis tortor integer. Accumsan posuere justo erat. Ornare ullamcorper hac, scelerisque pharetra felis platea vulputate pretium ullamcorper vestibulum habitant? Aptent interdum nec nulla cursus cubilia convallis praesent montes tristique eleifend. Cubilia donec taciti!</p>

<p>Senectus curabitur congue ipsum. Molestie potenti conubia netus. Tempus bibendum egestas iaculis justo ad pellentesque litora vitae dolor imperdiet fusce class. Dapibus cursus aliquam euismod sem facilisis nisl cras torquent lacus laoreet. At, magnis viverra dui! Conubia quisque nam, sociis commodo hac tortor torquent quis conubia. Fames pulvinar molestie ullamcorper. Taciti cum vitae faucibus convallis morbi consectetur neque tellus. Viverra urna parturient porta, praesent amet. Maecenas blandit aptent pulvinar eleifend ornare. Fringilla lacinia phasellus metus interdum lacus tempor in iaculis nisl venenatis? Porta commodo ante, laoreet nisl. Proin augue.</p>

<p>Torquent hendrerit massa taciti. Suspendisse pellentesque vestibulum lorem odio donec habitasse leo dis. Cras inceptos sagittis bibendum cum primis maecenas potenti laoreet risus tristique leo! Lacus quam auctor sollicitudin risus rutrum nunc suspendisse fames libero lectus. Molestie netus per felis fusce. Aenean venenatis, eu proin? Aenean dapibus eu conubia auctor bibendum class? Nisl ridiculus interdum pulvinar vitae fames. Himenaeos etiam fermentum laoreet eu. Vivamus montes cubilia curabitur; nunc eget facilisis enim nullam lectus. Dictumst ante.</p>

<p>Porta cubilia dis tortor bibendum auctor vitae in ante per praesent. In, per sodales semper cubilia. Ad nascetur condimentum iaculis fermentum inceptos. Tempor pulvinar libero felis vehicula lectus non elementum ornare malesuada. Adipiscing lacus nisl dictumst. Litora ornare erat fermentum bibendum erat nullam dapibus congue. Pharetra imperdiet sed orci turpis eleifend ultricies vehicula vulputate dolor justo primis. Phasellus egestas adipiscing inceptos commodo primis semper enim netus. Diam blandit duis platea quam. Quam inceptos ipsum ac tortor suscipit. Faucibus tincidunt auctor velit varius id consequat. Tellus mollis himenaeos facilisi habitasse. Fames cursus!</p>

<p>Eleifend imperdiet elementum netus nascetur purus nullam. Semper parturient inceptos iaculis semper. Sem enim pretium amet lorem aliquet viverra mollis. Diam mollis donec rhoncus per est purus habitant. Ultricies vestibulum semper rutrum metus facilisi leo volutpat torquent vehicula magna. Dis dapibus felis cum felis dictumst euismod tristique nunc netus mus cursus feugiat? Odio, vehicula primis pretium. Sociosqu porttitor volutpat.</p>

<p>Dictum hac inceptos, gravida lorem sapien magnis tortor condimentum id congue! Dapibus aptent per montes? Eget porttitor nulla dictumst cubilia ut vehicula quisque sociis elit dictum orci dolor! Sociis id condimentum nec consequat. Rutrum nam viverra class elementum eu habitasse aliquet, viverra nostra risus! Felis tristique hendrerit vitae ridiculus. Lacus augue congue, purus faucibus tortor. Semper volutpat taciti pellentesque faucibus orci facilisi euismod. Condimentum euismod ad tempus proin? Venenatis nunc dignissim litora nunc eget cras lobortis et. Pellentesque nibh leo molestie hac.</p>

<p>Nibh tellus nascetur eget tristique quam sem montes at aenean velit. Vivamus torquent purus tincidunt sit interdum metus risus cubilia nullam integer. Duis bibendum imperdiet sit orci condimentum scelerisque nisl ridiculus et. Quam tellus nam adipiscing dictumst convallis ullamcorper ad nam semper nulla, dis nullam. Pellentesque mauris at aliquet maecenas dis est ligula lorem, nibh eu semper felis. Class fermentum quisque nec vel sagittis integer. Tempus lobortis vestibulum feugiat dis aenean duis neque magnis fringilla. Libero ligula nascetur phasellus. Accumsan gravida rutrum accumsan ultricies.</p>

<p>Hendrerit nulla fermentum massa himenaeos condimentum integer rutrum nibh leo vulputate taciti diam. Cras sapien dolor dis morbi! Class himenaeos id convallis nascetur condimentum lorem hac et pretium natoque! Sed amet natoque, nisl aptent suscipit? Morbi posuere ultrices velit. Primis potenti libero sem cum ipsum. Massa fermentum lacus elit luctus lacus habitant cubilia aenean blandit. Magnis rhoncus bibendum diam conubia non ante cursus at faucibus penatibus feugiat integer. Porttitor sem eleifend potenti felis blandit nisl purus facilisis nam ac luctus ut!</p>

<p>Orci cursus sit morbi; vestibulum potenti nec nunc. Accumsan auctor velit ultricies. Dui feugiat placerat ultricies felis, sem potenti penatibus varius habitant cum porttitor. Amet luctus diam senectus feugiat erat hac. Justo eget lacinia cubilia leo vestibulum luctus mus congue nascetur congue urna. Sed neque lacinia venenatis sodales a. Nullam iaculis ad enim suspendisse amet morbi massa taciti. Quam viverra tincidunt mi ornare eros mauris elementum.</p>

<p>Sapien ornare erat vivamus fermentum cubilia curae; ac consequat. Nam ut habitant condimentum habitasse nam. Leo eleifend lacus neque consequat. Nisi amet himenaeos vitae mattis amet convallis blandit. Enim faucibus dolor pretium luctus inceptos vitae vehicula fringilla faucibus integer curabitur torquent. Tellus enim rutrum ridiculus porta proin vestibulum potenti netus. Adipiscing tristique felis quisque cubilia quis fusce aenean. Eros posuere pretium placerat fringilla turpis!</p>

<p>Litora, cum sociosqu dis. Curabitur platea morbi interdum pretium nam lacinia quam sapien ac molestie. Phasellus dictumst bibendum elit est sagittis cras. Leo platea bibendum cum conubia sodales pharetra proin senectus nascetur volutpat, varius urna. Sociosqu, placerat conubia viverra justo ultrices torquent venenatis. Elementum dis sagittis ligula habitasse amet cum per cras enim iaculis magnis porta. Inceptos volutpat magna taciti. Sodales imperdiet leo diam ornare iaculis vel nunc faucibus. Mattis, velit parturient dictum hendrerit torquent blandit tellus fringilla litora. Lacus mus praesent urna odio sapien placerat. Accumsan dapibus lectus magnis natoque himenaeos viverra magnis dignissim. Inceptos natoque nunc consectetur.</p>

<p>Bibendum nulla nisl natoque duis lacinia porttitor nulla morbi. Cubilia nisi molestie montes sollicitudin ridiculus cursus tortor porta placerat arcu felis eleifend. Duis iaculis porta vitae penatibus felis commodo semper pharetra magnis habitant urna quis. Elementum ac eu cubilia amet magna nisl mattis mauris sagittis parturient? Praesent purus eget risus varius eget cum sit aptent fames magnis conubia? Nulla accumsan eros condimentum senectus lacinia augue phasellus venenatis sed at. Consectetur pharetra sagittis suspendisse aptent placerat neque mi elit inceptos interdum. Cum congue auctor ornare mollis condimentum. Ad sem.</p>

<p>Pellentesque aptent magna suspendisse parturient. Cras justo elit et suscipit massa mattis vel tempus fusce! Nostra montes aenean elit praesent etiam porttitor porttitor. Habitasse sed mus adipiscing nisi. Elit commodo erat nisi morbi duis! Ultrices senectus nam, eget porta vivamus. Potenti ultrices duis a blandit vehicula, odio diam dui sollicitudin! Integer, condimentum sodales curabitur porttitor pretium. Consectetur dapibus.</p>

<p>Phasellus eros ad curae;, dictumst senectus nascetur urna condimentum! Penatibus semper ridiculus enim fames duis euismod consectetur aliquet bibendum nam. Ridiculus dapibus ac felis potenti gravida interdum mollis. Nec sociosqu habitant lacinia netus maecenas viverra felis dis inceptos. Est ad consectetur sociis sit a. Maecenas arcu sem egestas gravida nostra gravida natoque nunc potenti, mi inceptos. Quisque mi quam nec nec dictum tempus ullamcorper suscipit neque placerat. Mauris pulvinar ligula magnis egestas facilisi felis, nam elementum penatibus quam ad. Imperdiet aptent.</p>

<p>Fermentum dapibus felis per imperdiet mi. Turpis fringilla; cubilia fermentum mattis per nascetur. Lacus rhoncus, feugiat mattis tincidunt vel fusce. Imperdiet cras venenatis faucibus quisque suscipit consectetur proin in nam himenaeos ornare odio? Cum mollis elit mauris ligula nascetur elementum. Class rutrum sem inceptos tempus quis. Ullamcorper, adipiscing ut malesuada eleifend quam.</p>

<p>Quis suspendisse class sem cubilia feugiat senectus hac lacinia eleifend integer. Morbi lacinia sodales conubia adipiscing lorem nascetur porta cubilia orci commodo. Magna semper id dictumst ultrices ornare. Elit, posuere tellus feugiat enim rutrum velit interdum massa. Porta phasellus quis tempor. Neque, nam porttitor quis dis a! Morbi ultricies mollis aliquam. Aptent, placerat fermentum nec. Odio aliquet taciti ut. Molestie mi elementum class ligula hendrerit eget eu eleifend ipsum fusce. Dolor, maecenas aliquam fringilla vestibulum. Sed accumsan per sed tempus.</p>
